/**
 * Type definitions re-exported from WASM bindings.
 *
 * These types are generated by wasm-bindgen + tsify and correspond to the Rust types.
 */

// Re-export all types from the WASM module
// These are generated by wasm-bindgen and tsify
export type {
  Config,
  AnalysisResult,
  EffectEstimate,
  Diagnostics,
  AdaptiveStepResult,
  CalibrationHandle,
  AdaptiveStateHandle,
  TimerInfo,
  // Generated enum types (string unions)
  AttackerModel,
  Outcome,
  InconclusiveReason,
  Exploitability,
  MeasurementQuality,
} from "../pkg/tacet_wasm.js";

// Enum-like constants for ergonomic usage
// These match the string literal types from WASM

/** Attacker model determines the minimum effect threshold (theta).
 * Cycle-based thresholds use a 5 GHz reference frequency (conservative). */
export const AttackerModelValues = {
  /** theta = 0.4 ns (~2 cycles @ 5 GHz) - SGX, cross-VM, containers */
  SharedHardware: "sharedHardware" as const,
  /** theta = 2.0 ns (~10 cycles @ 5 GHz) - Post-quantum crypto */
  PostQuantum: "postQuantum" as const,
  /** theta = 100 ns - LAN, HTTP/2 (Timeless Timing Attacks) */
  AdjacentNetwork: "adjacentNetwork" as const,
  /** theta = 50 us - General internet */
  RemoteNetwork: "remoteNetwork" as const,
  /** theta -> 0 - Detect any difference (not for CI) */
  Research: "research" as const,
};

/** Test outcome values. */
export const OutcomeValues = {
  /** No timing leak detected within threshold theta. */
  Pass: "pass" as const,
  /** Timing leak detected exceeding threshold theta. */
  Fail: "fail" as const,
  /** Could not reach a decision. */
  Inconclusive: "inconclusive" as const,
  /** Operation too fast to measure reliably. */
  Unmeasurable: "unmeasurable" as const,
};

/** Reason for inconclusive result values. */
export const InconclusiveReasonValues = {
  /** Not applicable (outcome is not Inconclusive). */
  None: "none" as const,
  /** Posterior approximately equals prior after calibration. */
  DataTooNoisy: "dataTooNoisy" as const,
  /** Posterior stopped updating despite new data. */
  NotLearning: "notLearning" as const,
  /** Estimated time to decision exceeds budget. */
  WouldTakeTooLong: "wouldTakeTooLong" as const,
  /** Time budget exhausted. */
  TimeBudgetExceeded: "timeBudgetExceeded" as const,
  /** Sample limit reached. */
  SampleBudgetExceeded: "sampleBudgetExceeded" as const,
  /** Measurement conditions changed during test. */
  ConditionsChanged: "conditionsChanged" as const,
  /** Threshold was elevated due to measurement noise. */
  ThresholdElevated: "thresholdElevated" as const,
};

/** Exploitability assessment values. */
export const ExploitabilityValues = {
  /** < 10 ns - Requires shared hardware to exploit. */
  SharedHardwareOnly: "sharedHardwareOnly" as const,
  /** 10-100 ns - Exploitable via HTTP/2 request multiplexing. */
  Http2Multiplexing: "http2Multiplexing" as const,
  /** 100 ns - 10 us - Exploitable with standard remote timing. */
  StandardRemote: "standardRemote" as const,
  /** > 10 us - Obvious leak, trivially exploitable. */
  ObviousLeak: "obviousLeak" as const,
};

/** Measurement quality assessment values. */
export const MeasurementQualityValues = {
  /** MDE < 5 ns - Excellent measurement precision. */
  Excellent: "excellent" as const,
  /** MDE 5-20 ns - Good precision. */
  Good: "good" as const,
  /** MDE 20-100 ns - Poor precision. */
  Poor: "poor" as const,
  /** MDE > 100 ns - Too noisy for reliable detection. */
  TooNoisy: "tooNoisy" as const,
};
